name: Build Workflow

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Tornar Gradle executável
        run: chmod +x gradlew

      - name: Rodar Build (compilar o projeto)
        run: ./gradlew build

      - name: Rodar Testes
        run: ./gradlew test

      - name: Verificar Qualidade do Código (Check)
        run: ./gradlew check

      - name: Publicar Artefatos (JAR)
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
